### ISSUE TITLE
infinite loop on latest fw (1.4.0.1)

### ISSUE THREAD

**Issue by affadli** [RAKWireless/2.4GHz-LoRa-Node#5]
Hi, I'm facing issue with latest fw.
The firmware entering infinite loop on "INFO:Event received: ALARM" after "AT+JOIN". 
![image](https://github.com/RAKWireless/2.4GHz-LoRa-Node/assets/68206349/41606c57-a4a3-4dc6-8fad-1bab77789c2c)

So, I cannot sent any data after joined, the mote also not able to receive any command.
after I reverted to fw 1.0.2.4, its working properly.
Is this normal behavior?

**Comment by yanwenlan** [comment]
Hi, @affadli  Sorry for the late reply. This problem is caused by the interval not having an initial value. You can execute "AT+INTERVAL=0" before executing "AT+JOIN" or use our latest code to compile, thanks
